#!/bin/bash
rm -rf ~/sgoinfre/docker

rm -rf ~/Library/Containers/com.docker.docker
mkdir -p /Users/cpaquet/goinfre/docker/com.docker.docker
ln -s /Users/cpaquet/goinfre/docker/com.docker.docker ~/Library/Containers/com.docker.docker

rm -rf ~/.docker
mkdir -p /Users/cpaquet/goinfre/docker/.docker
ln -s /Users/cpaquet/goinfre/docker/.docker ~/.docker
